args <- commandArgs(TRUE)
suppressPackageStartupMessages({library(dplyr); library(purrr)})
source(args[1])
g <- read.csv(args[2])
g$rate_r <- mapply(function(m, s, pl) koa_gate_rate(m, s, origin = pl), g$m, g$sdi, g$planted)
g$absdiff <- abs(g$rate_r - g$rate_py)
write.csv(g, args[3], row.names = FALSE)
cat(sprintf("MORT PARITY max abs diff %.3g over %d points, version %s\n", max(g$absdiff), nrow(g), VersionTag))
stopifnot(max(g$absdiff) < 1e-12)
